//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PropertyDetail
{
    public PropertyDetail()
    {
        this.PropertyImages = new HashSet<PropertyImage>();
    }

    public int PropertyID { get; set; }
    public short TypeID { get; set; }
    public short SubtypeID { get; set; }
    public decimal Price { get; set; }
    public int Size { get; set; }
    public string FloorLevel { get; set; }
    public short BedroomQty { get; set; }
    public short BathroomQty { get; set; }
    public short TenureID { get; set; }
    public string Developer { get; set; }
    public System.DateTime ListedDate { get; set; }
    public string MRT { get; set; }
    public string School { get; set; }
    public string ChildCare { get; set; }
    public string Description { get; set; }
    public string CreateUser { get; set; }

    public virtual ICollection<PropertyImage> PropertyImages { get; set; }
    public virtual PropertySubtype PropertySubtype { get; set; }
    public virtual PropertyTenure PropertyTenure { get; set; }
    public virtual PropertyType PropertyType { get; set; }
}

public partial class PropertyImage
{
    public int ImageID { get; set; }
    public Nullable<int> PropertyID { get; set; }
    public string PropertyImage1 { get; set; }

    public virtual PropertyDetail PropertyDetail { get; set; }
}

public partial class PropertyLocation
{
    public int PropertyID { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Region { get; set; }
    public string Country { get; set; }
    public string CountryCode { get; set; }
    public string PostalCode { get; set; }
    public decimal Latitude { get; set; }
    public decimal Longitude { get; set; }
    public Nullable<int> AgentID { get; set; }
}

public partial class PropertySubtype
{
    public PropertySubtype()
    {
        this.PropertyDetails = new HashSet<PropertyDetail>();
    }

    public short SubtypeID { get; set; }
    public short TypeID { get; set; }
    public string Subtype { get; set; }

    public virtual ICollection<PropertyDetail> PropertyDetails { get; set; }
}

public partial class PropertyTenure
{
    public PropertyTenure()
    {
        this.PropertyDetails = new HashSet<PropertyDetail>();
    }

    public short TenureID { get; set; }
    public string TenureType { get; set; }

    public virtual ICollection<PropertyDetail> PropertyDetails { get; set; }
}

public partial class PropertyType
{
    public PropertyType()
    {
        this.PropertyDetails = new HashSet<PropertyDetail>();
    }

    public short TypeID { get; set; }
    public string Type { get; set; }

    public virtual ICollection<PropertyDetail> PropertyDetails { get; set; }
}
