//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PropertyDbEntities : DbContext
{
    public PropertyDbEntities()
        : base("name=PropertyDbEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<PropertyDetail> PropertyDetails { get; set; }
    public virtual DbSet<PropertyImage> PropertyImages { get; set; }
    public virtual DbSet<PropertyLocation> PropertyLocations { get; set; }
    public virtual DbSet<PropertySubtype> PropertySubtypes { get; set; }
    public virtual DbSet<PropertyTenure> PropertyTenures { get; set; }
    public virtual DbSet<PropertyType> PropertyTypes { get; set; }
}
